/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_cassandra_thrift_Hello */

#ifndef _Included_org_apache_cassandra_thrift_Hello
#define _Included_org_apache_cassandra_thrift_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_cassandra_thrift_Hello
 * Method:    HelloWorld
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_cassandra_thrift_Hello_HelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
